[package]
name = "sparc"
version = "0.1.0"
authors = ["Jeehoon Kang <jeehoon.kang@sf.snu.ac.kr>"]
edition = "2018"

[dependencies]
rayon = "1.0.3"

[dependencies.nom]
version = "4.2.0"
features = ["regexp"]
